### ISSUE TITLE
picojson eats one too many characters when parsing a number

### ISSUE THREAD

**Issue by ChrisJefferson** [kazuho/picojson#92]
Error: When the string begins with a number, parsing eats one too many characters.

Consider the string `2x`. When picojson parses this it does:

Start reading number: Get `2`, fine. Get `x`, end of number, call `ungetc`, return.
However, the character in the `ungetc` buffer gets dropped, and I have no way to access it. The return pointer points one past the `x`, so when I use to check if my whole buffer was parsed correctly, everything is fine.

**Comment by ChrisJefferson** [comment]
I think this is (almost) impossible to fix neatly, because if we assume we are using input iterators, then the character is gone. However, we can at least provide a way of accessing the lost character..

**Comment by kazuho** [comment]
Sorry I do not get this.

It is true that ECMAScript allows a literal without surrounding (double)quotes to be used as a key of an object, it has been always illegal in [JSON](https://tools.ietf.org/html/rfc7159).

And we do not have any plans to support relaxed encoding rules (since it might open up a can of interoperability _and security_ issues).

**Comment by ChrisJefferson** [comment]
Ignore my whole rambling.

I'm talking about the bug which was fixed in #73, which I hadn't updated to. Sorry.
